#!/usr/bin/env bash
# Install nginx on a web-server and config a custom HTTP header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y install nginx-extras
sudo sed -i 's/# server_tokens off;/server_tokens off;\n\tmore_set_headers "X-Served-By: $HOSTNAME";/' /etc/nginx/nginx.conf
sudo service nginx restart
