#!/usr/bin/env bash
# install and config HAproxy
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get update
sudo apt-get install -y haproxy
echo -e "\nfrontend localnodes\n\tbind *:80\n\tmode http\n\tdefault_backend nodes" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\nbackend nodes\n\tmode http\n\thttp-request set-header X-Forwarded-Port %[dst_port]\n\tbalance roundrobin\n\toption forwardfor\n\tserver 320-web-01 35.229.28.8:80 check\n\tserver 320-web-02 35.231.1.19:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
