#!/usr/bin/env bash
# Using your previous exercise command, write a Bash script that displays line containing the bash word, this allowing you to easily get the PID of your Bash process
# shellcheck disable=SC2009
./1-list_your_processes | grep bash
