#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
x=1
while [ $x -le 10 ]
do
    if [ $x -ne 9 ]
    then
	echo "Holberton School"
    else
	echo "Hi"
    fi
    x=$((x + 1))
done
