#!/usr/bin/env bash
# install nginx and run as nginx user
sudo apt-get -y install nginx
sudo useradd nginx 2>/dev/null
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo service nginx start
